export const projects = [
  {
    id: 1,
    projectName: "EduConnect",
    projectDescription:
      "A collaborative and productive platform for workers in the educational sector where they can share their works, experiences, tips & tricks, and other insightful ideas.",
    status: "Done",
    isDeployed: true,
    projectImage: "/projects/EduConnect.png",
    projectUrl: "https://educonnect-ten.vercel.app/ ",
    type: "Collaboration",
    type2: "Web",
    techs:
      "Next JS, Nest JS, MongoDB, Socket.Io, Zustand, Cloudinary, Shadcn UI, Tailwind CSS, Git",
    coDev1: "Carl James Roxas",
    coDev2: "Kevin Roy Sta Cruz",
    finishedDate: "04-20-2024",
  },
  {
    id: 2,
    projectName: "Portfolio",
    projectDescription:
      "An application for managing tasks, including features like task creation, assignment, deadline tracking, and progress monitoring.",
    status: "Completed",
    isDeployed: true,
    projectImage: "/projects/portfolio.png",
    projectUrl: "https://portfolio-noah-mark.vercel.app/",
    type: "Web",
    techs: "Next JS, Tailwind CSS, Git",
    finishedDate: "04-22-2024",
  },
  {
    id: 3,
    projectName: "Smart Plastic Bottle Bin",
    projectDescription:
      "Our Capstone Project is a cutting-edge web application designed to complement our IoT-based Reverse Vending Machine for plastic bottles. From its inception, through planning, designing, and development, this project has been a testament to our commitment to advancing web development skills and delivering high-quality projects.",
    status: "DONE",
    isDeployed: true,
    projectImage: "/projects/SmartBin.png",
    projectUrl: "https://www.smartbottlebin.online/",
    type: "Collaboration",
    type2: "Web",
    techs: "Next JS, React JS, Supabase, Shadcn UI, Tailwind CSS, Vercel, Git",
    finishedDate: "11-22-2023",
  },
  {
    id: 4,
    projectName: "Loan Management System",
    projectDescription:
      "Our Django web application project, developed as part of our Web System and Technologies 3 course, is a sophisticated loan management system designed to streamline the process of recording loans and payments for clients.",
    status: "Done",
    isDeployed: false,
    projectImage: "/projects/loan.png",
    projectUrl: "https://educonnect-ten.vercel.app/ ",
    type: "Collaboration",
    type2: "Web",
    techs: "Python, Django Framework, SQLite, Tailwind, JQuery, HTML, Git, MVC",
    finishedDate: "12-16-2023",
  },
  {
    id: 5,
    projectName: "CareMed",
    projectDescription:
      "I made a landing page as a practice for the Frontend web development coding contest.",
    status: "Done",
    isDeployed: true,
    projectImage: "/projects/caremed.png",
    projectUrl: "https://solid-adventure-meek.vercel.app/",
    type: "Web",
    techs: "Next JS, Shadcn UI, Tailwind CSS, Git",
    finishedDate: "11-18-2023",
  },
  // {
  //   id: 6,
  //   projectName: "Booktopia",
  //   projectDescription:
  //     "I made a landing page as a practice for the Frontend web development coding contest.",
  //   status: "Done",
  //   isDeployed: true,
  //   projectImage: "/projects/dtr.png",
  //   projectUrl: "https://booktopia-kappa.vercel.app/",
  //   type: "Web",
  //   techs: "Next JS, Supabase, Shadcn UI, Tailwind CSS, Git",
  //   finishedDate: "02-20-2024",
  // },
  {
    id: 6,
    projectName: "Daily Time Record",
    projectDescription:
      "I made a Daily time record system that can be used as the attendance for students and employees.",
    status: "Done",
    isDeployed: true,
    projectImage: "/projects/dtr.png",
    projectUrl: "https://dtr-two.vercel.app/",
    type: "Web",
    techs: "Next JS, Supabase, Shadcn UI, Tailwind CSS, Git",
    finishedDate: "02-20-2024",
  },
];
